const requests = {
    fetchUserInfo: "/api/user/info",
    fetchUserApprove: "/api/user/approval",
    fetchEmployeeCount: "/api/employee/admin/count",
    fetchEmployeeList: "/api/employee/admin/all",
    fetchEmployeeDeveloper: "/api/employee/admin/developer",
    fetchEmployeeElse: "/api/employee/admin/else",
    fetchEmployeeSearch: "/api/employee/admin/search",
    fetchProjectCount: "/api/admin/project/count",
    fetchEmployeeProjectCount: "/api/project/count",
    fetchProjectList: "/api/admin/project/search",
    fetchProjectListEmployee: "/api/admin/project/search",
    fetchProjectDetail: "/api/project",
    fetchEmployeeProjectList: "/api/project",
    fetchEmployeeProjectComplete: "/api/project/done/1",
    fetchEmployeeProjectInProgress: "/api/project/in-progress",
    fetchEmployeeProjectDone: "/api/project/done",
    fetchProjectEvaluation: "/api/evaluation/project/list",
    fetchPossibleEvaluateProject: "/api/evaluation/projects",
    fetchPossibleEvaluateCheck: "/api/evaluation/check",
    fetchEvaluationDetail: "/api/evaluation/info",
    fetchManpowerList: "/api/manpower",
    fetchManpowerPossibleListEdit: "/api/manpower/admin/edit/available/all",
    fetchManpowerPossibleListNew: "/api/manpower/admin/new/available/all",
    fetchManpowerSearch: "/api/manpower/admin/new/available/search",
};

export default requests;
